# Generated by Django 2.2.10 on 2020-03-20 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200320_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasure',
            name='user',
        ),
    ]
